#!/usr/bin/env python3
"""
mhr-ggate | Config Generator

Builds three artifacts in one shot:
  1. client_config.json     -> xray client config (talks to LOCAL relay)
  2. relay.toml             -> client_relay.py config (talks to GAS)
  3. mhr.vmess              -> single shareable vmess:// link

Usage:
  python3 generate_config.py \
      --gas-url https://script.google.com/macros/s/XXX/exec \
      --secret  YOUR_SHARED_SECRET \
      --uuid    YOUR_UUID

If you don't pass --uuid a fresh one will be generated.
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import re
import sys
import textwrap
import uuid
from pathlib import Path
from urllib.parse import urlparse

# ─── DEFAULTS ───────────────────────────────────────────────
DEFAULT_GAS_URL    = "https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec"
DEFAULT_PATH       = "/mhr"
DEFAULT_RELAY_PORT = 8000
DEFAULT_SOCKS_PORT = 1080
DEFAULT_HTTP_PORT  = 8118
# ──────────────────────────────────────────────────────────

UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


def is_uuid(value: str) -> bool:
    return bool(value) and bool(UUID_RE.match(value))


def parse_gas(gas_url: str) -> tuple[str, str, str]:
    parsed = urlparse(gas_url)
    if parsed.scheme not in ("http", "https"):
        raise ValueError(f"gas_url must be http/https: {gas_url!r}")
    if not parsed.netloc:
        raise ValueError(f"gas_url is missing host: {gas_url!r}")
    return parsed.scheme, parsed.netloc, parsed.path or "/"


def build_client_config(*, vmess_uuid: str, path: str,
                        relay_port: int, socks_port: int, http_port: int) -> dict:
    """xray config that points at the LOCAL relay, not GAS directly."""
    return {
        "log": {"loglevel": "warning"},
        "inbounds": [
            {
                "tag": "socks-in",
                "port": socks_port,
                "listen": "127.0.0.1",
                "protocol": "socks",
                "settings": {"auth": "noauth", "udp": True, "ip": "127.0.0.1"},
                "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]}
            },
            {
                "tag": "http-in",
                "port": http_port,
                "listen": "127.0.0.1",
                "protocol": "http",
                "sniffing": {"enabled": True, "destOverride": ["http", "tls"]}
            }
        ],
        "outbounds": [
            {
                "tag": "mhr-ggate",
                "protocol": "vmess",
                "settings": {
                    "vnext": [{
                        "address": "127.0.0.1",      # local relay
                        "port": relay_port,
                        "users": [{
                            "id": vmess_uuid,
                            "alterId": 0,
                            "security": "auto"
                        }]
                    }]
                },
                "streamSettings": {
                    "network": "xhttp",
                    "xhttpSettings": {
                        "path": path,
                        "mode": "packet-up",
                        "scMaxEachPostBytes": 1000000,
                        "scMaxConcurrentPosts": 100,
                        "scMinPostsIntervalMs": 30
                    }
                },
                "mux": {
                    "enabled": True,
                    "concurrency": 8,
                    "xudpConcurrency": 16,
                    "xudpProxyUDP443": "allow"
                }
            },
            {"tag": "direct", "protocol": "freedom", "settings": {}},
            {"tag": "block",  "protocol": "blackhole"}
        ],
        "routing": {
            "domainStrategy": "IPIfNonMatch",
            "rules": [
                {"type": "field", "ip": ["geoip:private"], "outboundTag": "direct"},
                {"type": "field", "domain": ["geosite:category-ads-all"], "outboundTag": "block"},
                {"type": "field", "network": "tcp,udp", "outboundTag": "mhr-ggate"}
            ]
        }
    }


def build_relay_toml(*, gas_url: str, secret: str, port: int) -> str:
    return textwrap.dedent(f"""\
        # mhr-ggate client relay config
        # generated by generate_config.py

        gas_url           = "{gas_url}"
        secret            = "{secret}"
        listen_host       = "127.0.0.1"
        listen_port       = {port}
        upstream_timeout  = 60.0
        max_retries       = 2
        retry_backoff     = 0.4
        log_level         = "INFO"
        metrics_enabled   = true
    """)


def build_vmess_link(*, vmess_uuid: str, path: str, relay_port: int,
                     remark: str = "mhr-ggate") -> str:
    """vmess:// link that targets the LOCAL relay.

    This is for clients (v2rayN/Hiddify) that don't use our generated
    client_config.json — they will still go through 127.0.0.1:relay_port.
    """
    payload = {
        "v":    "2",
        "ps":   remark,
        "add":  "127.0.0.1",
        "port": str(relay_port),
        "id":   vmess_uuid,
        "aid":  "0",
        "scy":  "auto",
        "net":  "xhttp",
        "type": "none",
        "host": "",
        "path": path,
        "tls":  "",
        "sni":  "",
        "alpn": "",
        "fp":   "",
        "mode": "packet-up"
    }
    encoded = base64.urlsafe_b64encode(
        json.dumps(payload, separators=(",", ":")).encode()
    ).rstrip(b"=").decode()
    return f"vmess://{encoded}"


def write_files(out_dir: Path, *, client_cfg: dict, relay_toml: str,
                vmess_link: str) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = {
        "client_config": out_dir / "client_config.json",
        "relay_toml":    out_dir / "relay.toml",
        "vmess_link":    out_dir / "mhr.vmess",
    }
    paths["client_config"].write_text(json.dumps(client_cfg, indent=2), encoding="utf-8")
    paths["relay_toml"].write_text(relay_toml, encoding="utf-8")
    paths["vmess_link"].write_text(vmess_link + "\n", encoding="utf-8")
    return paths


def banner(args, vmess_uuid: str, written: dict[str, Path]) -> str:
    return textwrap.dedent(f"""
        ============================================================
          mhr-ggate | configs generated
        ============================================================

          UUID         : {vmess_uuid}
          GAS URL      : {args.gas_url}
          Path         : {args.path}
          Relay port   : 127.0.0.1:{args.relay_port}
          SOCKS5       : 127.0.0.1:{args.socks_port}
          HTTP         : 127.0.0.1:{args.http_port}

          xray config  : {written['client_config']}
          relay config : {written['relay_toml']}
          vmess link   : {written['vmess_link']}

        next steps:
          1. start the local relay:
               python3 v2ray/client_relay.py --config {written['relay_toml']}
          2. start xray:
               xray run -config {written['client_config']}
          3. point your apps at SOCKS5 127.0.0.1:{args.socks_port}
             or HTTP 127.0.0.1:{args.http_port}
        ============================================================
    """).strip("\n")


def main() -> int:
    p = argparse.ArgumentParser(description="mhr-ggate config generator")
    p.add_argument("--gas-url",    default=DEFAULT_GAS_URL,
                   help="Google Apps Script /exec URL")
    p.add_argument("--secret",     default=os.environ.get("MHR_SECRET", ""),
                   help="shared secret with VPS (or set MHR_SECRET)")
    p.add_argument("--uuid",       default=None,
                   help="VMess UUID (one will be generated if omitted)")
    p.add_argument("--path",       default=DEFAULT_PATH,
                   help="xhttp path on the xray server (default /mhr)")
    p.add_argument("--relay-port", type=int, default=DEFAULT_RELAY_PORT)
    p.add_argument("--socks-port", type=int, default=DEFAULT_SOCKS_PORT)
    p.add_argument("--http-port",  type=int, default=DEFAULT_HTTP_PORT)
    p.add_argument("--out-dir",    default=".",
                   help="directory for the generated files")
    args = p.parse_args()

    # validation
    errors = []
    if "YOUR_SCRIPT_ID" in args.gas_url:
        errors.append("--gas-url is still the placeholder; set the real /exec URL")
    if not args.secret or args.secret == "CHANGE_THIS_SECRET_KEY":
        errors.append("--secret is empty; pass --secret or set MHR_SECRET")
    try:
        parse_gas(args.gas_url)
    except ValueError as exc:
        errors.append(str(exc))
    if args.uuid and not is_uuid(args.uuid):
        errors.append(f"--uuid is malformed: {args.uuid!r}")
    if errors:
        for e in errors:
            print(f"[!] {e}", file=sys.stderr)
        return 2

    vmess_uuid = args.uuid or str(uuid.uuid4())
    client_cfg = build_client_config(
        vmess_uuid=vmess_uuid,
        path=args.path,
        relay_port=args.relay_port,
        socks_port=args.socks_port,
        http_port=args.http_port,
    )
    relay_toml = build_relay_toml(
        gas_url=args.gas_url,
        secret=args.secret,
        port=args.relay_port,
    )
    vmess_link = build_vmess_link(
        vmess_uuid=vmess_uuid,
        path=args.path,
        relay_port=args.relay_port,
    )

    out_dir = Path(args.out_dir).resolve()
    written = write_files(out_dir,
                          client_cfg=client_cfg,
                          relay_toml=relay_toml,
                          vmess_link=vmess_link)
    print(banner(args, vmess_uuid, written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
